### ISSUE TITLE
Another MediatR?

### ISSUE THREAD

**Issue by ajukraine** [mayuanyang/Mediator.Net#1]
Hi @mayuanyang 
what's the difference between this project and https://github.com/jbogard/MediatR ?
They seem to implement same idea.

**Comment by mayuanyang** [comment]
Hi,  thanks for your question,  the key difference is Mediator. net has got pipelines which you can plug in as many middlewares as want to deal with cross cutting concern,  e.g I can put in serilog into the global pipeline so that every message get logged before it reached its handlers, I can also plug in EventStore into the publish pipe to save every message to EventStore,  another good example is plug in unit of work so that developers do not need to handle transaction explicitly. Mediator. Net has got many different pipelines as shown in the picture in the readme file
Cheers

**Comment by cecilphillip** [comment]
I was wondering the same thing as well. MediatR has some support for pipelines now through [Behaviors](https://github.com/jbogard/MediatR/wiki/Behaviors). The approach is a bit different, but it's here.

Ultimately, there's a's choice. Use what you like 👍

**Comment by mayuanyang** [comment]
thanks for your information, looks like a new feature before i build Mediator.Net, very good source to learn. will dig in a bit more😀

**Comment by mayuanyang** [comment]
As there is no more response,  I am going to close it now
